### PR TITLE
Adjust a bug

### PR DESCRIPTION
**Pull request by A-Miracle**
CropUtils: java.lang.IllegalArgumentException: width and height must be > 0

### CODE REVIEW

**Comment by alexvasilkov** [comment]
It looks like workaround, what the real issue you want to fix with it?
In which case you're getting IllegalArgumentException?

**Comment by A-Miracle** [comment]
I'm sorry, I could not find the root cause of the problem, It may be just a rough idea of the solution

**Comment by alexvasilkov** [comment]
Ok, anyway, thank you!
Do you have any details for that issue, i.e. steps to reproduce or full stacktrace?

**Comment by A-Miracle** [comment]
I just tried again, no problem. My code may be wrong. Sorry

**Comment by alexvasilkov** [comment]
Ok, I'll consider to add a check and throw more developer friendly exception in this case

**Comment by A-Miracle** [comment]
Ok, thank you

**Pull request closed without merging**
